name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 🚨 Breaking changes
    exclusive: true
    when:
      label: breaking-change

  - title: 🚀 Features
    exclusive: true
    when:
      labels:
        - feature
        - enhancement

  - title: 🐛 Bug Fixes
    exclusive: true
    when:
      label: bugfix

  - title: 🧰 Misc
    exclusive: true
    when:
      labels:
        - chore
        - documentation

  - title: ⬆️ Dependency updates
    exclusive: true
    collapse-after: 0
    when:
      label: dependencies

  # Exclude these from the release notes
  - type: pre-exclude
    when:
      labels:
        - skip-changelog

  # Version resolution
  - type: version-resolver
    semver-increment: major
    when:
      label: major

  - type: version-resolver
    semver-increment: minor
    when:
      labels:
        - minor
        - breaking-change

  - type: version-resolver
    semver-increment: patch
    when:
      labels:
        - patch
        - feature
        - enhancement

  # Fallback
  - type: version-resolver
    semver-increment: patch

exclude-contributors:
  - jwnmulder

autolabeler:
  - label: enhancement
    branch:
      - '/feature\/.+/'
  - label: bugfix
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'

change-template: '* $TITLE (#$NUMBER) by @$AUTHOR'
template: |
  $CHANGES
