name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
exclude-labels:
  - dependencies
categories:
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bugfix
      - bug
  - title: 🧰 Maintenance
    labels:
      - chore
      - documentation
  - title: 💥 Breaking changes
    labels:
      - breaking-change
exclude-contributors:
  - jwnmulder
autolabeler:
  - label: documentation
    files:
      - '*.md'
    branch:
      - '/docs\/.+/'
  - label: enhancement
    branch:
      - '/feature\/.+/'
  - label: fix
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - feature
      - enhancement
  patch:
    labels:
      - patch
  default: patch
change-template: '* $TITLE (#$NUMBER)'
template: |
  ## Changes

  $CHANGES
