exclude: ".*/(data|testdata)/.*"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-json
        exclude: ".vscode/.*"
      - id: check-yaml
        files: .*\.(yaml|yml)$
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.9.0.6
  #   hooks:
  #     - id: shellcheck

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --strict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args:
          - --fix
          - --fixable
          - I

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.5
    hooks:
      - id: uv-lock

  # - repo: https://github.com/RobertCraigie/pyright-python
  #   rev: v1.1.396
  #   hooks:
  #     - id: pyright
