# mqtt:
#   host:
#   port:

dbus:
  subscriptions:
    - bus_name: org.mpris.MediaPlayer2.*
      path: /org/mpris/MediaPlayer2

      # https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html
      interfaces:
        - interface: org.freedesktop.DBus.Properties
          # signals:
          #     # with no postprocessing, just use handlers otherwise
          #   - signal: PropertiesChanged  # simple forwarding of signal to mqtt
          #     mqtt_signal_topic: dbus2mqtt/org.mpris.MediaPlayer2/signal/PropertiesChanged
          signal_handlers:
            # TODO: allow for trigger by timer
            # Position property updates do not trigger a PropertiesChange event
            - signal: PropertiesChanged
              filter: "{{ args[0] == 'org.mpris.MediaPlayer2.Player' }}"
              payload_template: |
                {{ dbus_call('org.freedesktop.DBus.Properties', 'GetAll', 'org.mpris.MediaPlayer2.Player') }}
              mqtt_topic: dbus2mqtt/org.mpris.MediaPlayer2/state
            - signal: PropertiesChanged
              filter: "{{ args[0] == 'org.mpris.MediaPlayer2.Player' }}"
              payload_template: |
                interface_name: {{ args[0] }}
                changed_properties:
                  {{ args[1] | to_nice_yaml | indent(2) }}
                invalidated_properties: {{ args[2] }}
                properties:
                  {{ dbus_call('org.freedesktop.DBus.Properties', 'GetAll', 'org.mpris.MediaPlayer2') }}
                player_properties:
                  {{ dbus_call('org.freedesktop.DBus.Properties', 'GetAll', 'org.mpris.MediaPlayer2.Player') }}
              # mqtt_topic: dbus2mqtt/{{ bus_name }}/state
              mqtt_topic: dbus2mqtt/org.mpris.MediaPlayer2/debug
          methods:
            - method: GetAll

        - interface: org.mpris.MediaPlayer2
          mqtt_call_method_topic: dbus2mqtt/org.mpris.MediaPlayer2/command
          methods:
            - method: Quit

        - interface: org.mpris.MediaPlayer2.Player
          mqtt_call_method_topic: dbus2mqtt/org.mpris.MediaPlayer2/command
          # bus_name_selection: first/all/...
          methods:
            - method: Pause
            - method: Play
            - method: PlayPause
            - method: OpenUri
            - method: Stop
          properties:
            - property: Metadata
            - property: Volume

# handlers:
#   - name: mpris_on_properties_changes
#     triggers:
#       - schedule: 5s
#       - on_signal:
#           interface: org.freedesktop.DBus.Properties
#           signal: PropertiesChanged
#           filter: "{{ args[0] == 'org.mpris.MediaPlayer2.Player' }}"
#     actions:
#       - publish_mqtt:
#           topic: dbus2mqtt/org.mpris.MediaPlayer2/debug
#           payload: |
#             {{ dbus_call('org.freedesktop.DBus.Properties', 'GetAll', 'org.mpris.MediaPlayer2.Player') }}
