# mqtt:
#   host:
#   port:

dbus:
  subscriptions:
    - bus_name: org.mpris.MediaPlayer2.*
      path: /org/mpris/MediaPlayer2
      interfaces:
        - interface: org.freedesktop.DBus.Properties
          signals:
            - signal: PropertiesChanged
              filter: "{{ args[0] == 'org.mpris.MediaPlayer2.Player' }}"
              payload_template: |
                interface_name: {{ args[0] }}
                changed_properties:
                  {{ args[1] | to_nice_yaml | indent(2) }}
                invalidated_properties: {{ args[2] }}
        - interface: org.mpris.MediaPlayer2
          methods:
            - method: Quit
            
        - interface: org.mpris.MediaPlayer2.Player
          methods:
            - method: Pause
            - method: Play
            - method: OpenUri
            - method: Stop
          properties:
            - property: Metadata
            - property: Volume
