site_name: dbus2mqtt
site_description: General purpose DBus to MQTT bridge
site_url: https://jwnmulder.github.io/dbus2mqtt
site_author: Jan-Willem Mulder
copyright: Copyright © Jan-Willem Mulder 2025
repo_name: jwnmulder/dbus2mqtt
repo_url: https://github.com/jwnmulder/dbus2mqtt
edit_uri: edit/main/docs/
# strict: true

# Some examples to have a look at
# https://github.com/mkdocstrings/mkdocstrings/blob/main/mkdocs.yml
# https://github.com/twpayne/chezmoi/blob/master/assets/chezmoi.io/mkdocs.yml
# https://github.com/facelessuser/pymdown-extensions/blob/main/mkdocs.yml

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  language: en
  features:
    # - navigation.expand
    # - navigation.indexes
    # - navigation.sections
    # - navigation.tabs
    # - navigation.top
    # - content.tabs.link
    # - navigation.tracking
    - announce.dismiss
    # - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    # - content.code.annotations

nav:
  - Home: index.md
  # - User guide:
  # - installation - docker
  - Flows: flows.md
  # - References:
  - Examples:
      - examples.md
      - examples/home_assistant_media_player.md
      - examples/bluez.md
      # - examples/dbus2mqtt_internal_state.md
      # - examples/linux_desktop.md

  - Developer guide:
      - debugging.md

# https://facelessuser.github.io/pymdown-extensions
markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
