FROM python:3.14-slim-bookworm@sha256:5404df00cf00e6e7273375f415651837b4d192ac6859c44d3b740888ac798c99

WORKDIR /app

ARG DBUS2MQTT_VERSION=latest

RUN pip install --no-cache-dir dbus2mqtt=="$DBUS2MQTT_VERSION"

ENTRYPOINT ["python", "-m", "dbus2mqtt"]

# show help message by default
CMD ["--help"]
