FROM python:3.14-slim-bookworm@sha256:9ab8d9c8514b44f90cf0029dd42fdd7e9e211e639c8b995304cc04568dee900f

WORKDIR /app

ARG DBUS2MQTT_VERSION=latest

RUN pip install --no-cache-dir dbus2mqtt=="$DBUS2MQTT_VERSION"

ENTRYPOINT ["python", "-m", "dbus2mqtt"]

# show help message by default
CMD ["--help"]
