name: pre-commit

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: "pyproject.toml"
      - uses: pre-commit/action@v3.0.1
